config/routes.rb
Rails.application.routes.draw do
  root 'chat_rooms#index'
  resources :chat_rooms do
    member do
      post '/join' => 'chat_rooms#join'
      post '/chat' => 'chat_rooms#chat'
      delete '/exit' => 'chat_rooms#exit'
    end
  end

  devise_for :users

end

app/models/admission.rb
class Admission < ActiveRecord::Base
  belongs_to :user
  belongs_to :chat_room, counter_cache: true

  after_commit :join_chat_room_notification, on: :create
  after_commit :exit_chat_room_notification, on: :destroy
  def join_chat_room_notification
    Pusher.trigger('chat_room', 'join', self.as_json)
    Pusher.trigger("chat_room_#{self.chat_room_id}", 'join', self.as_json.merge({email: self.user.email, chat_room: self.chat_room.as_json}))
  end

  def exit_chat_room_notification
    Pusher.trigger('chat_room', 'exit', self.as_json)
    Pusher.trigger("chat_room_#{self.chat_room_id}",'exit',self.as_json.merge({email: self.user.email, chat_room: self.chat_room.as_json}))
  end
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  belongs_to :chat_room

  after_commit :chat_message_notification, on: :create

  def chat_message_notification
    Pusher.trigger("chat_room_#{self.chat_room_id}", 'chat', self.as_json.merge({email: self.user.email}))
  end
end

app/models/chat_room.rb
class ChatRoom < ActiveRecord::Base
  # chat과 1:N 관계
  has_many :chats
  # user와 M:N 관계
  has_many :user, through: :admissions
  has_many :admissions, dependent: :destroy

  after_commit :create_chat_room_notification, on: :create
  #생성하는 commit이 발생했을 때에만 after_commit 메소드가 실행
  after_commit :destroy_chat_room_notification, on: :destroy

  def create_chat_room_notification
    #Pusher.trigger(채널명, 이벤트명, 정보 json)
    Pusher.trigger('chat_room', 'create', self.as_json)
  end

  def destroy_chat_room_notification
    Pusher.trigger('chat_room', 'destroy', self.as_json)
    Pusher.trigger("chat_room_#{self.id}", 'destroy', {})
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #chat 이랑 1:N
  has_many :chats
  #chat_room 과 M:N
  has_many :admissions
  has_many :chat_rooms, through: :admissions

  def join_room?(chatroom)
    # Admission.where(user_id: self.id, chat_room_id: chatroom.id)
    self.chat_rooms.include?(chatroom)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:show, :edit, :update, :destroy, :join, :chat, :exit]

  # GET /chat_rooms
  # GET /chat_rooms.json
  def index
    @chat_rooms = ChatRoom.all
  end

  # GET /chat_rooms/1
  # GET /chat_rooms/1.json
  def show
  end

  # GET /chat_rooms/new
  def new
    @chat_room = ChatRoom.new
  end

  # GET /chat_rooms/1/edit
  def edit
  end

  # POST /chat_rooms
  # POST /chat_rooms.json
  def create
    @chat_room = ChatRoom.new(chat_room_params)
    @chat_room.master_id = current_user.email

    respond_to do |format|
      if @chat_room.save
        Admission.create(user_id: current_user.id, chat_room_id: @chat_room.id)
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully created.' }
        format.json { render :show, status: :created, location: @chat_room }
      else
        format.html { render :new }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_rooms/1
  # PATCH/PUT /chat_rooms/1.json
  def update
    respond_to do |format|
      if @chat_room.update(chat_room_params)
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat_room }
      else
        format.html { render :edit }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_rooms/1
  # DELETE /chat_rooms/1.json
  def destroy
    @chat_room.destroy
    respond_to do |format|
      format.html { redirect_to chat_rooms_url, notice: 'Chat room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def join
    unless current_user.join_room?(@chat_room)
      Admission.create(user_id: current_user.id, chat_room_id: params[:id])
    else
      render js: "alert('이미 참여한 방입니다.')"
    end
  end

  def chat
    @chat_room.chats.create(user_id: current_user.id, message: params[:message])
  end

  def exit
    if current_user.email == @chat_room.master_id
      @chat_room.destroy
    else
      addmission = Admission.find_by(user_id: current_user.id, chat_room_id: @chat_room.id)
      addmission.destroy
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_room
      @chat_room = ChatRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_room_params
      params.require(:chat_room).permit(:title, :master_id, :max_count, :admissions_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/_form.html.erb
<%= form_for(@chat_room) do |f| %>
  <% if @chat_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat_room.errors.count, "error") %> prohibited this chat_room from being saved:</h2>

      <ul>
      <% @chat_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <!-- <div class="field">
    <%#f.label :master_id %><br>
    <%# f.text_field :master_id %>
  </div> -->
  <div class="field">
    <%= f.label :max_count %><br>
    <%= f.number_field :max_count %>
  </div>
  <!-- <div class="field">
    <%# f.label :admissions_count %><br>
    <%# f.number_field :admissions_count %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chat_rooms/edit.html.erb
<h1>Editing Chat Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat_room %> |
<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/exit.js.erb
alert('방을 나갔습니다.');
location.href = '/';

app/views/chat_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chat Rooms</h1>

<table>
  <thead>
    <tr>
      <th>방제</th>
      <th>방장</th>
      <th>인원</th>
      <!-- <th>Admission count</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="chat_room_list">
    <% @chat_rooms.each do |chat_room| %>
      <tr id = "chat_room_<%= chat_room.id %>">
        <td><%= chat_room.title %></td>
        <td><%= chat_room.master_id %></td>
        <td class = ""><%= chat_room.admissions_count %>/<%= chat_room.max_count %></td>
        <td><%= link_to 'Show', chat_room %></td>
        <td><%= link_to 'Edit', edit_chat_room_path(chat_room) %></td>
        <td><%= link_to 'Destroy', chat_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat room', new_chat_room_path %>

<script type="text/javascript">

  $(document).on('ready', function(){
    var pusher = new Pusher("<%= ENV['pusher_key'] %>", {
    cluster: "<%= ENV['pusher_cluster']  %>",
    encrypted: true
    });

    function room_add(data){
        $('.chat_room_list').append(`
          <tr>
            <td>${data.title}</td>
            <td>${data.master_id}</td>
            <td>${data.admissions_count}/${data.max_count}</td>
            <td><a href="/chat_rooms/${data.id}">Show</a></td>
            <td><a href="/chat_rooms/${data.id}/edit">Edit</a></td>
            <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/chat_rooms/${data.id}">Destroy</a></td>
          </tr>
          `);
    }

    var channel = pusher.subscribe('chat_room');
    channel.bind('create', function(data) {
      //방 리스트에 추가
      room_add(data);
    });

    // channel.bind('join', function(data) {
    //   // 인원 추가
    //
    // });
    //
    // channel.bind('exit', function(data) {
    //   //인원 아웃
    //
    // });
    //
    // channel.bind('destroy', function(data) {
    //   //방삭
    //
    // });
  });

</script>

app/views/chat_rooms/join.js.erb
alert('입장하셨슴다~');
location.reload();

app/views/chat_rooms/new.html.erb
<h1>New Chat Room</h1>

<%= render 'form' %>

<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>방제:</strong>
  <%= @chat_room.title %>
</p>

<p>
  <strong>방장:</strong>
  <%= @chat_room.master_id %>
</p>

<p>
  <strong>인원:</strong>
  <span class="count"><%= @chat_room.admissions_count %>/<%= @chat_room.max_count %></span>
</p>

<hr />
<p class="user-list"><strong>참여 인원</strong></p>
<% @chat_room.user.each do |user| %>
  <p id="user-<%= user.id %>"><%= user.email %></p>
<% end %>
<hr/>

<% if current_user.join_room? @chat_room %>
  <div class="chat-list">
    <% @chat_room.chats.each do |chat| %>
    <p><%= chat.user.email %> : <%= chat.message %></p>
    <% end %>
  </div>
  <hr/>
  <%= form_tag(chat_chat_room_path(@chat_room), remote: true) do %>
    <%= text_field_tag :message %>
  <% end %>
<% end %>

<% unless current_user.join_room? @chat_room %>
  <%= link_to '입장하기', join_chat_room_path(@chat_room), remote: true, method: 'post' %>
<% else %>
  <%= link_to '나가기', exit_chat_room_path(@chat_room),remote: true, method: 'delete', data: {confirm: '나가니??'} %>
<% end %>

<%= link_to 'Edit', edit_chat_room_path(@chat_room) %> |
<%= link_to 'Back', chat_rooms_path %>

<script type="text/javascript">

  $(document).on('ready', function(){
    function user_join(data){
      $('.user-list').append(`<p>${data.email}</p>`)
      $('.count').text(`${data.chat_room.admissions_count}/${data.chat_room.max_count}`);
    }

    function user_chat(data){
      $('.chat-list').append(`<p>${data.email} : ${data.message}</p>`)
    }

    function user_exit(data){
      $('.chat-list').append(`<p>${data.email}님이 퇴장하셨습니다.</p>`)
      $('.count').text(`${data.chat_room.admissions_count}/${data.chat_room.max_count}`);
      $(`#user-${data.user_id}`).remove();
    }

    function room_destroy(data){
      alert('방이 삭제되었습니다. 홈으로 이동합니다.');
      location.href = "/";
    }

    var pusher = new Pusher("<%= ENV['pusher_key'] %>", {
    cluster: "<%= ENV['pusher_cluster']  %>",
    encrypted: true
    });


    var channel = pusher.subscribe('chat_room_<%= @chat_room.id %>');
    channel.bind('create', function(data) {
      room_created(data);
    });

    channel.bind('join', function(data) {
      //들어온 유저를 유저 참여 목록에 추가한다.
      user_join(data);
    });

    channel.bind('chat', function(data) {
      //들어온 유저를 유저 참여 목록에 추가한다.
      user_chat(data);
    });

    channel.bind('exit', function(data) {
      //들어온 유저를 유저 참여 목록에 추가한다.
      user_exit(data);
    });

    channel.bind('destroy', function(data) {
      //들어온 유저를 유저 참여 목록에 추가한다.
      room_destroy(data);
    });

  });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatservice</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
</head>
<body>
<% if user_signed_in? %>
  <p><%= current_user.email %></p>
   <%= link_to '로그아웃', destroy_user_session_path, method: :delete %>
<% else %>
     <%= link_to '로그인', new_user_session_path %>
     <%= link_to '회원가입', new_user_registration_path %>
<% end %>
<%= yield %>

</body>
</html>